import type { Metadata } from 'next';

import ClientLayout from '../styles/ClientLayout';
import CssBaseline from '@mui/material/CssBaseline';

import '../styles/globals.css';

export const metadata: Metadata = {
	title: 'Avionics Spaceport America',
	description: 'Generated by create next app',
	icons: {
<<<<<<< HEAD
		icon: '/svg/icon.svg',
=======
		icon: '/svg/rocketIcon.svg',
>>>>>>> 35ee9b5a6da7bd530b0bf745efe983aa825f0054
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<CssBaseline />
				<ClientLayout>{children}</ClientLayout>
			</body>
		</html>
	);
}
